# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(948, 617)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ro_read_btn = QtWidgets.QPushButton(Form)
        self.ro_read_btn.setMaximumSize(QtCore.QSize(0, 0))
        self.ro_read_btn.setObjectName("ro_read_btn")
        self.verticalLayout.addWidget(self.ro_read_btn)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.plot_combobox = QtWidgets.QComboBox(self.groupBox_6)
        self.plot_combobox.setObjectName("plot_combobox")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.gridLayout_3.addWidget(self.plot_combobox, 1, 0, 1, 4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 4)
        self.arg_start = QtWidgets.QLineEdit(self.groupBox_6)
        self.arg_start.setObjectName("arg_start")
        self.gridLayout_3.addWidget(self.arg_start, 3, 1, 1, 1)
        self.arg_end = QtWidgets.QLineEdit(self.groupBox_6)
        self.arg_end.setObjectName("arg_end")
        self.gridLayout_3.addWidget(self.arg_end, 3, 3, 1, 1)
        self.plot_btn = QtWidgets.QPushButton(self.groupBox_6)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout_3.addWidget(self.plot_btn, 4, 0, 1, 4)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.plot_widget = QtWidgets.QWidget(Form)
        self.plot_widget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_widget.sizePolicy().hasHeightForWidth())
        self.plot_widget.setSizePolicy(sizePolicy)
        self.plot_widget.setMinimumSize(QtCore.QSize(700, 400))
        self.plot_widget.setMaximumSize(QtCore.QSize(16777208, 16777215))
        self.plot_widget.setBaseSize(QtCore.QSize(1000, 400))
        self.plot_widget.setObjectName("plot_widget")
        self.horizontalLayout_2.addWidget(self.plot_widget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ro_a = QtWidgets.QLineEdit(self.groupBox)
        self.ro_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ro_a.setObjectName("ro_a")
        self.gridLayout_2.addWidget(self.ro_a, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.ro_b = QtWidgets.QLineEdit(self.groupBox)
        self.ro_b.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ro_b.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ro_b.setStatusTip("")
        self.ro_b.setWhatsThis("")
        self.ro_b.setInputMask("")
        self.ro_b.setMaxLength(32769)
        self.ro_b.setObjectName("ro_b")
        self.gridLayout_2.addWidget(self.ro_b, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setLineWidth(0)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 3)
        self.read_ro_btn = QtWidgets.QPushButton(self.groupBox)
        self.read_ro_btn.setObjectName("read_ro_btn")
        self.gridLayout_2.addWidget(self.read_ro_btn, 3, 0, 2, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 2, 1)
        self.s_expr = QtWidgets.QLineEdit(self.groupBox_4)
        self.s_expr.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.s_expr.setStatusTip("")
        self.s_expr.setWhatsThis("")
        self.s_expr.setInputMask("")
        self.s_expr.setText("")
        self.s_expr.setMaxLength(32769)
        self.s_expr.setObjectName("s_expr")
        self.gridLayout_5.addWidget(self.s_expr, 1, 1, 2, 2)
        self.read_s_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.read_s_btn.setObjectName("read_s_btn")
        self.gridLayout_5.addWidget(self.read_s_btn, 4, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 0, 0, 1, 3)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.z_expr = QtWidgets.QLineEdit(self.groupBox_3)
        self.z_expr.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.z_expr.setStatusTip("")
        self.z_expr.setWhatsThis("")
        self.z_expr.setInputMask("")
        self.z_expr.setText("")
        self.z_expr.setMaxLength(32769)
        self.z_expr.setObjectName("z_expr")
        self.gridLayout_7.addWidget(self.z_expr, 1, 1, 2, 2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 2, 1)
        self.read_z_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.read_z_btn.setObjectName("read_z_btn")
        self.gridLayout_7.addWidget(self.read_z_btn, 4, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 3, 0, 1, 3)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Мего приложение по ЧМ"))
        self.ro_read_btn.setText(_translate("Form", "Считать"))
        self.groupBox_6.setTitle(_translate("Form", "Графики"))
        self.label_4.setText(_translate("Form", "аргумент:"))
        self.label_6.setText(_translate("Form", "до"))
        self.label_5.setText(_translate("Form", "от"))
        self.plot_combobox.setItemText(0, _translate("Form", "ro"))
        self.plot_combobox.setItemText(1, _translate("Form", "x"))
        self.plot_combobox.setItemText(2, _translate("Form", "S"))
        self.plot_combobox.setItemText(3, _translate("Form", "z"))
        self.plot_combobox.setItemText(4, _translate("Form", "x - S"))
        self.plot_combobox.setItemText(5, _translate("Form", "y"))
        self.plot_combobox.setItemText(6, _translate("Form", "С1"))
        self.plot_combobox.setItemText(7, _translate("Form", "C2"))
        self.arg_start.setText(_translate("Form", "-10"))
        self.arg_end.setText(_translate("Form", "10"))
        self.plot_btn.setText(_translate("Form", "Построить"))
        self.groupBox.setTitle(_translate("Form", "r(t)"))
        self.ro_a.setText(_translate("Form", "1"))
        self.label.setText(_translate("Form", "b = "))
        self.ro_b.setToolTip(_translate("Form", "<html><head/><body><p>Имя файла...</p></body></html>"))
        self.ro_b.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "a = "))
        self.label_3.setText(_translate("Form", "ro(w) = aw(b - w)"))
        self.read_ro_btn.setText(_translate("Form", "Задать"))
        self.groupBox_5.setTitle(_translate("Form", "x(t)"))
        self.groupBox_4.setTitle(_translate("Form", "S(t)"))
        self.label_7.setText(_translate("Form", "S(t) = "))
        self.s_expr.setToolTip(_translate("Form", "<html><head/><body><p>Имя файла...</p></body></html>"))
        self.read_s_btn.setText(_translate("Form", "Задать"))
        self.groupBox_3.setTitle(_translate("Form", "z(t)"))
        self.z_expr.setToolTip(_translate("Form", "<html><head/><body><p>Имя файла...</p></body></html>"))
        self.label_8.setText(_translate("Form", "z(t) = "))
        self.read_z_btn.setText(_translate("Form", "Задать"))
        self.groupBox_2.setTitle(_translate("Form", "y(t)"))

