# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1082, 719)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ro_read_btn = QtWidgets.QPushButton(Form)
        self.ro_read_btn.setMaximumSize(QtCore.QSize(0, 0))
        self.ro_read_btn.setObjectName("ro_read_btn")
        self.gridLayout_4.addWidget(self.ro_read_btn, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 4)
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 4)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 4)
        self.arg_start = QtWidgets.QLineEdit(self.groupBox_6)
        self.arg_start.setObjectName("arg_start")
        self.gridLayout_3.addWidget(self.arg_start, 3, 1, 1, 1)
        self.plot_btn = QtWidgets.QPushButton(self.groupBox_6)
        self.plot_btn.setObjectName("plot_btn")
        self.gridLayout_3.addWidget(self.plot_btn, 4, 0, 1, 4)
        self.arg_end = QtWidgets.QLineEdit(self.groupBox_6)
        self.arg_end.setObjectName("arg_end")
        self.gridLayout_3.addWidget(self.arg_end, 3, 3, 1, 1)
        self.plot_combobox = QtWidgets.QComboBox(self.groupBox_6)
        self.plot_combobox.setObjectName("plot_combobox")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.plot_combobox.addItem("")
        self.gridLayout_3.addWidget(self.plot_combobox, 1, 0, 1, 4)
        self.gridLayout_9.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.groupBox_9 = QtWidgets.QGroupBox(Form)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.start_btn = QtWidgets.QPushButton(self.groupBox_9)
        self.start_btn.setObjectName("start_btn")
        self.gridLayout_16.addWidget(self.start_btn, 1, 0, 1, 1)
        self.auto_mode = QtWidgets.QCheckBox(self.groupBox_9)
        self.auto_mode.setObjectName("auto_mode")
        self.gridLayout_16.addWidget(self.auto_mode, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        self.tab.setMinimumSize(QtCore.QSize(800, 400))
        self.tab.setObjectName("tab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.plot_widget = QtWidgets.QWidget(self.tab)
        self.plot_widget.setObjectName("plot_widget")
        self.gridLayout_17.addWidget(self.plot_widget, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.plot_trajectory = QtWidgets.QWidget(self.tab_2)
        self.plot_trajectory.setObjectName("plot_trajectory")
        self.gridLayout_18.addWidget(self.plot_trajectory, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_19.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.plot_filt = QtWidgets.QWidget(self.tab_3)
        self.plot_filt.setObjectName("plot_filt")
        self.gridLayout_19.addWidget(self.plot_filt, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 2, 1, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ro_a = QtWidgets.QLineEdit(self.groupBox)
        self.ro_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ro_a.setObjectName("ro_a")
        self.gridLayout_2.addWidget(self.ro_a, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.ro_b = QtWidgets.QLineEdit(self.groupBox)
        self.ro_b.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ro_b.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.ro_b.setStatusTip("")
        self.ro_b.setWhatsThis("")
        self.ro_b.setInputMask("")
        self.ro_b.setMaxLength(32769)
        self.ro_b.setObjectName("ro_b")
        self.gridLayout_2.addWidget(self.ro_b, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setLineWidth(0)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 3)
        self.read_ro_btn = QtWidgets.QPushButton(self.groupBox)
        self.read_ro_btn.setEnabled(False)
        self.read_ro_btn.setObjectName("read_ro_btn")
        self.gridLayout_2.addWidget(self.read_ro_btn, 3, 0, 2, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.s_expr = QtWidgets.QLineEdit(self.groupBox_4)
        self.s_expr.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.s_expr.setStatusTip("")
        self.s_expr.setWhatsThis("")
        self.s_expr.setInputMask("")
        self.s_expr.setMaxLength(32769)
        self.s_expr.setObjectName("s_expr")
        self.gridLayout_5.addWidget(self.s_expr, 1, 1, 2, 2)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 2, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 0, 0, 1, 3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 5, 0, 1, 3)
        self.read_s_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.read_s_btn.setEnabled(False)
        self.read_s_btn.setObjectName("read_s_btn")
        self.gridLayout_5.addWidget(self.read_s_btn, 3, 0, 2, 3)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem7, 0, 0, 1, 3)
        self.z_expr = QtWidgets.QLineEdit(self.groupBox_3)
        self.z_expr.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.z_expr.setStatusTip("")
        self.z_expr.setWhatsThis("")
        self.z_expr.setInputMask("")
        self.z_expr.setMaxLength(32769)
        self.z_expr.setObjectName("z_expr")
        self.gridLayout_7.addWidget(self.z_expr, 1, 1, 2, 2)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 1, 0, 2, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem8, 5, 0, 1, 3)
        self.read_z_btn = QtWidgets.QPushButton(self.groupBox_3)
        self.read_z_btn.setEnabled(False)
        self.read_z_btn.setObjectName("read_z_btn")
        self.gridLayout_7.addWidget(self.read_z_btn, 3, 0, 2, 3)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.gridLayout_10.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 0, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem11, 0, 4, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_12.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_7)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_12.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_7)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_12.addWidget(self.label_11, 2, 0, 1, 1)
        self.y0 = QtWidgets.QLineEdit(self.groupBox_7)
        self.y0.setObjectName("y0")
        self.gridLayout_12.addWidget(self.y0, 1, 1, 1, 1)
        self.x0 = QtWidgets.QLineEdit(self.groupBox_7)
        self.x0.setObjectName("x0")
        self.gridLayout_12.addWidget(self.x0, 0, 1, 1, 1)
        self.T = QtWidgets.QLineEdit(self.groupBox_7)
        self.T.setObjectName("T")
        self.gridLayout_12.addWidget(self.T, 2, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_6)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem12, 0, 0, 1, 2)
        self.beta = QtWidgets.QLineEdit(self.groupBox_8)
        self.beta.setObjectName("beta")
        self.gridLayout_14.addWidget(self.beta, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.gridLayout_14.addWidget(self.label_12, 1, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem13, 2, 0, 1, 2)
        self.gridLayout_15.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_8, 0, 3, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem14, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout_4.addWidget(self.tabWidget, 3, 1, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Мего приложение по ЧМ"))
        self.ro_read_btn.setText(_translate("Form", "Считать"))
        self.groupBox_6.setTitle(_translate("Form", "Графики"))
        self.label_4.setText(_translate("Form", "аргумент:"))
        self.label_6.setText(_translate("Form", "до"))
        self.label_5.setText(_translate("Form", "от"))
        self.arg_start.setText(_translate("Form", "-10"))
        self.plot_btn.setText(_translate("Form", "Построить"))
        self.arg_end.setText(_translate("Form", "10"))
        self.plot_combobox.setItemText(0, _translate("Form", "ro"))
        self.plot_combobox.setItemText(1, _translate("Form", "x"))
        self.plot_combobox.setItemText(2, _translate("Form", "S"))
        self.plot_combobox.setItemText(3, _translate("Form", "z"))
        self.plot_combobox.setItemText(4, _translate("Form", "x - S"))
        self.plot_combobox.setItemText(5, _translate("Form", "y"))
        self.plot_combobox.setItemText(6, _translate("Form", "С1"))
        self.plot_combobox.setItemText(7, _translate("Form", "C2"))
        self.groupBox_9.setTitle(_translate("Form", "Модель"))
        self.start_btn.setText(_translate("Form", "Запуск"))
        self.auto_mode.setText(_translate("Form", "Автоматический режим"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Form", "Графики"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form", "Траектория"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "Параметр фильтрации"))
        self.groupBox.setTitle(_translate("Form", "r(t)"))
        self.ro_a.setText(_translate("Form", "1"))
        self.label.setText(_translate("Form", "b = "))
        self.ro_b.setToolTip(_translate("Form", "<html><head/><body><p>Имя файла...</p></body></html>"))
        self.ro_b.setText(_translate("Form", "1"))
        self.label_2.setText(_translate("Form", "a = "))
        self.label_3.setText(_translate("Form", "ro(w) = aw(b - w)"))
        self.read_ro_btn.setText(_translate("Form", "Задать"))
        self.groupBox_4.setTitle(_translate("Form", "S(t)"))
        self.s_expr.setToolTip(_translate("Form", "<html><head/><body><p>Имя файла...</p></body></html>"))
        self.s_expr.setText(_translate("Form", "t**2"))
        self.label_7.setText(_translate("Form", "S(t) = "))
        self.read_s_btn.setText(_translate("Form", "Задать"))
        self.groupBox_3.setTitle(_translate("Form", "z(t)"))
        self.z_expr.setToolTip(_translate("Form", "<html><head/><body><p>Имя файла...</p></body></html>"))
        self.z_expr.setText(_translate("Form", "np.sqrt(t)"))
        self.label_8.setText(_translate("Form", "z(t) = "))
        self.read_z_btn.setText(_translate("Form", "Задать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Функции"))
        self.groupBox_7.setTitle(_translate("Form", "Начальные значения"))
        self.label_10.setText(_translate("Form", "Y0 = "))
        self.label_9.setText(_translate("Form", "X0 = "))
        self.label_11.setText(_translate("Form", "T = "))
        self.y0.setText(_translate("Form", "1"))
        self.x0.setText(_translate("Form", "1"))
        self.T.setText(_translate("Form", "10"))
        self.groupBox_8.setTitle(_translate("Form", "Beta"))
        self.label_12.setText(_translate("Form", "beta = "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "Параметры"))

